model = "gpt-5.6-sol"
model_reasoning_effort = "high"
model_provider = "custom-gateway"

[model_providers.custom-gateway]
name = "AMD LLM Gateway"
base_url = "https://llm-api.amd.com/OpenAI"
wire_api = "responses"
# Maps the header name to an environment variable name
env_http_headers = { "Ocp-Apim-Subscription-Key" = "AMD_LLM_API_KEY" }

[features]
multi_agent = true
apps = true
[tui]
animations = false

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 2
[sandbox_workspace_write]
# TODO: remove this once Codex lets you make a command do a sandbox escape.
network_access = true
writable_roots = [
    "/home/kdrewnia/.cache/ccache/",
    "/home/krzys/.cache/ccache/",
    "/home/kdrewnia/reviews/",
    "/home/krzys/reviews/",
    "/home/kdrewnia/iree/main/iree/.git",
    "/home/kdrewnia/llvm/main/llvm-project/.git",
    "/home/krzys/llvm/main/llvm-project/.git",
    "/home/kdrewnia/.codex/",
    "/home/krzys/.codex/"
]
